### ISSUE TITLE
Could you please help identify these colors?

### ISSUE THREAD

**Issue by mkanet** [Box-Of-Hats/VSCode_ThemeDesigner#7]
Hi, I hope it's okay to contact you this way.  On Reddit you mentioned that the best way to get a hold of you is here. 

When building a theme extension with yo Theme builder., I noticed when I specify to build a theme that's **"dark"** (importing my existing TextMate colors), in the extension it creates a file called, "package.json" where it specifies, _"uiTheme": "vs-dark"_ in that file.

When building the same exact theme as above, except I specify to build a theme that's **"light"** (importing my existing TextMate colors), in the extension it creates a file called, "package.json" where it specifies   _"uiTheme": "vs"_ in that file.

Do you know where the resources _"uiTheme": "vs-dark"_ and _"uiTheme": "vs"_ are located?  They seem to specify what basic/general colors meant for either a dark or light theme (when building a color theme extension).  I would like to know where these files are located in order to further customize my colors.

I found a folder below which I thought might be related.  However, I'm not sure:
*\resources\app\extensions\theme-defaults\themes

Do you have any ideas what/where these resources are below?
_"uiTheme": "vs-dark"_ and _"uiTheme": "vs"_ 

Thanks for any help you might be able to offer!

**Comment by Box-Of-Hats** [comment]
If you open the theme picker in VSCode (Ctrl + Shift + P, 'Preferences: Color Theme'), you can then pick either the default light or dark themes.
![image](https://user-images.githubusercontent.com/9083502/60136292-ad9d4100-979b-11e9-972f-f0f9cb77a94a.png)

From there, you can generate a color theme from that setting (Ctrl + Shift + P, 'Developer: Generate a color theme from these settings'. This will give you a JSON file that will contain the full settings of either 'vs-dark' or 'vs'.

Hope this helped :)

**Comment by mkanet** [comment]
Thanks for replying back so quickly!  

Just so you know... I've defined most of my syntax highlighting colors when importing my TextMate colors and building my theme using "yo theme generator".  Plus, I defined many of my colors also in my user settings.json file.  The remainder of my colors were supplemented using the basic dark theme in VScode.

Do you know of a way for me to find out what colors I did NOT define in my theme extension and user settings.json files  _(...the ones that came from the basic dark theme)_?

Those are the only colors I have left to define.. .but not sure what they're called.  I couldn't identify them using [.](https://code.visualstudio.com/api/references/theme-color)  

I might be able to get the delta by creating a json file (using the suggestion you mentioned).

Thanks for all your time and help!

**Comment by mkanet** [comment]
I exported the workspaces for both light and dark themes (also including my custom colors) using "Developer: Generator a color theme from these settings" feature.  Then, created a patch file based on the diff between the two ...which gave me the result I wanted.

Is there an online resource which describes theme color components more thoroughly than  [https://code.visualstudio.com/api/references/theme-color](url)?  Below is the link to all the colors I still need to figure out. In a perfect world, your website would have ALL these items.  I'm open to suggestions.  Otherwise, its gonna be a painful trial and error way to determine where all these colors are.

Here are all the colors I need to figure out:
**https://mka.mka.net/sp2**
