### ISSUE TITLE
"editor.foreground"

### ISSUE THREAD

**Issue by mkanet** [Box-Of-Hats/VSCode_ThemeDesigner#8]
Sorry to keep bugging you.  I am 99% finished with my theme.  However, I ran into a snag....

All I'm trying to do is use light-colored text on my **"Find/Replace" widget**" so I can actually see it on a dark background. See screenshot below where it where says, _"No Results"_ on the Find widget.
I was able to do that by defining a light color to **"editor.foreground":** to my user settings.json file.
When I went to look at my code... to my horror it had also changed a significant color for syntax highlighting. See screenshot below where some of my code becomes unreadable.

I'm sure there must be a way to define the color to these two things separately. Could you please tell me how to adjust the "No Results" text for my find/replace widget without affecting how my code looks? Seems pretty lame that the two items are even at all related. And no... I don't want to change my background colors in case you might want to suggest that. :) Thank in advance!

![EditorForeground](https://user-images.githubusercontent.com/811008/60232772-750c6e80-9852-11e9-9267-0e28adfdd09e.jpg)

**Comment by Box-Of-Hats** [comment]
I'm really not sure on this one sorry. I've not done much in terms of customising the colors of code but I'd suspect that there's certain tokens (like operators?) that inherit the `editor.foreground` colour if one isnt specified. I'd recommend looking at your token customisations and seeing if there's a way of changing the color of the code text

**Comment by mkanet** [comment]
Thank you so much for getting back to me.  Ill see if there's a way to change my theme file.. if I can find the right token for this.
I really appreciate all your help!
